sudo: required
language: php
php: 7.0
before_install: phpize
install: ./configure --prefix=/usr && sudo make install
before_script:
  - for PORT in 6379 6380 6381 6382; do /usr/bin/redis-server --port $PORT --daemonize yes; done
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - php tests/TestRedis.php --class Redis
  - php tests/TestRedis.php --class RedisArray
